# Generated by Django 5.1.2 on 2024-12-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='service',
        ),
    ]
