# Generated by Django 5.1.2 on 2024-12-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicerequest_service'),
        ('users', '0002_alter_company_field_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='hour',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
